BUILD_DEPS =        \
  build-essential   \
  cmake             \
  pkg-config        \
  bison             \
  gcc-mingw-w64     \
  libxml2-dev       \
  libglib2.0-dev    \
  libgpgme-dev      \
  libgcrypt20-dev   \
  libgnutls28-dev   \
  libssh-gcrypt-dev \
  libpcap-dev       \
  libsnmp-dev       \
  libradcli-dev     \
  libldap2-dev      \
  libhiredis-dev    \
  libksba-dev       \
  uuid-dev          \
  libpq-dev         \
  libical-dev       \
  libnet-dev        \
  libmicrohttpd-dev \
  heimdal-dev       \
  libpopt-dev       \
  libunistring-dev  \
  gnutls-bin        \
  xml-twig-tools    \
  xsltproc          \
  xmltoman          \
  clang-format      \
  doxygen           \
  graphviz          \
  python3-pip       \
  python3-venv      \
  postgresql-server-dev-all
