#!/bin/bash

### stop all services

############################################################
function show_msg() {
	echo -e "\033[31m === $1 \033[0m"
}
############################################################

show_msg "stop gsad.service"
systemctl stop    gsad
systemctl disable gsad

show_msg "stop gvmd.service"
systemctl stop    gvmd
systemctl disable gvmd

show_msg "stop ospd-openvas.service"
systemctl stop    ospd-openvas
systemctl disable ospd-openvas

show_msg "stop thp_never.service"
systemctll stop   thp_never
systemctl disable thp_never

show_msg "stop redis-server@openvas.service"
systemctll stop   redis-server@openvas
systemctl disable redis-server@openvas

show_msg "stop postgresql.service"
systemctll stop   postgresql
systemctl disable postgresql
